- hosts: all
  tasks:

  - name:
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward

  - name:
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward = 1'

  - name: first
    shell: firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o {{intake_interface}} -j MASQUERADE
    register: first

  - name: second
    shell: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{outtake_interface}} -o {{intake_interface}} -j ACCEPT
    register: second

  - name: third
    shell: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{intake_interface}} -o {{outtake_interface}} -m state RELATED,ESTABLISHED -j ACCEPT
    register: third

  - debug: var=first.stdout_lines

  - debug: var=second.stdout_lines

  - debug: var=third.stdout_lines